### ISSUE TITLE
[SOLVED] Need Way To push to DockerHub, preferrably in Jupyter Org

### ISSUE THREAD

**Issue by hamelsmu** [jupyterhub/repo2docker-action#37]
@betatim @choldgraf 

Part of the [release process](https://github.com/jupyterhub/repo2docker-action/blob/master/.github/workflows/docker.yaml) of this Action is materializing all the dependencies for this Action.  Two issues:

1. Currently, this action is linked to [github/repo2docker-action](https://hub.docker.com/repository/docker/github/repo2docker-action), but this should probably be in Jupyter so that Jupyter has control over it?

2. I would need someone (an admin) to add the secrets to this repository `DOCKER_USERNAME` and `DOCKER_PASSWORD`

This is the workflow in this repository `.github/workflows/docker.yaml`
```yaml
name: Docker
on: 
  push:
    branches:
      - master

jobs:
  build-action-container:
    runs-on: ubuntu-latest
    steps:

      - name: Get repo contents
        uses: actions/checkout@v2

      - name: docker login
        run: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            ./build_action_container.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
```

Can someone help me with this?

# CORRECTION

Ooops I forgot that I don't actually need this!  I made some changes in anticipation that this would happen and am forcing folks to build the container each time the action starts.  So the action is actually no longer referencing `github/repo2docker-action`

Therefore I don't need any help.  I guess I should stop trying to work late at night.  My apologies for the noise.
