### ISSUE TITLE
[Bug] Docker image doesn't get rebuilt when using GitHub Packages

### ISSUE THREAD

**Issue by Paveloom** [jupyterhub/repo2docker-action#51]
**Describe the bug**

Here's a clear example of my [workflow](https://github.com/paveloom-j/Scats.jl/pull/129/checks?check_run_id=932680151) (.yml configuration below): I have two images getting built together, one for GitHub Packages, the other for Docker Hub. The latter is used for Binder, so this action specifies a value for `BINDER_CACHE`. If an honest image assembly is visible in the step for Docker Hub, then there is no one in the step for GitHub Packages. See pictures or visit links below for a more detailed view. In [this pull request](https://github.com/paveloom-j/Scats.jl/pull/129) I was going to install TeX dependencies inside the images. In the image for Docker Hub everything is fine, all packages have been installed. In the image for GitHub Packages none of the packages were installed, and it's even difficult to tell which version of the repository this image contains. What is happening in this step is the action pulls the last image from GitHub Packages registry and just updates its tag. There is no real rebuild.

**To Reproduce**

My current workflow looks like this:

```yml
jobs:
  Binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push to GitHub Packages
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: "docker.pkg.github.com"
        IMAGE_NAME: "paveloom-j/scats.jl/binder"

    - name: Build and push to Docker Hub
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: paveloom
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        COMMIT_MSG: "Binder: update the image tag."
        PUBLIC_REGISTRY_CHECK: true
        IMAGE_NAME: "paveloom/scats.jl-binder"
```
It's difficult to test, so it's probably better to use existing logs.

**Expected behavior**

I'd like to see reassembly of the image as it happens with Docker Hub.

**Screenshots**

<details>
<summary>GitHub Packages</summary>
<p></p>
<img src="https://i.imgur.com/BfToePe.png">
</details>

<details>
<summary>Docker Hub</summary>
<p></p>
<img src="https://i.imgur.com/ZEJul3g.png">
</details>

**Additional context**

Logs:
* [GitHub Packages](https://github.com/paveloom-j/Scats.jl/runs/932680151#step:4:153)
* [Docker Hub](https://github.com/paveloom-j/Scats.jl/runs/932680151#step:5:35)

**Comment by hamelsmu** [comment]
My understanding is this an issue with GitHub packages and not with this Action?   You might want to contact GitHub support or open an issue somewhere for GitHub package registry?

**Comment by Paveloom** [comment]
I'm not sure about that. If I take away the image assembly for Docker Hub, it'll be all right for GitHub Packages. As, for example, in this [pull request](https://github.com/paveloom-j/Scats.jl/pull/118). All builds were repeated, as expected. Here's [an example](https://github.com/paveloom-j/Scats.jl/runs/926772832#step:4:157) of one of them.
 
Something happens when both of these actions are together. Any idea what might lead to image getting pulled?

**Comment by hamelsmu** [comment]
Oh I think I understand now you are trying to push the same image to multiple registries?  The repo2docker Action is running inside a Docker container so this is why any artifacts created are not visible to subsequent steps because they aren’t written back out to the host.  We would have to write the image out as a file onto disk to have it available like that in a second step.

Maybe for your advanced use case you use repo2docker directly inside Actions and not this Action?  That will give you more flexibility

**Comment by Paveloom** [comment]
> Oh I think I understand now you are trying to push the same image to multiple registries?

Not quite the way you understood it. I do want to build the same image for multiple registries, but in doing so I want it to happen independently of each other. That is, I want to build the same image from scratch twice, once for each registry. Yeah, it's kind of a waste of time, but not the point, hehe.

I was playing with these actions now: split them into two different jobs, then into two different workflows, then left only the action for GitHub Packages. And here I discovered what I think will narrow the search area of the problem: **the image is not built unless a value for `BINDER_CACHE` is specified.**

Example 1:

Workflow file:

```yml
jobs:
  BinderGHP:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push to GitHub Packages
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: "docker.pkg.github.com"
        IMAGE_NAME: "paveloom-j/scats.jl/binder"
```

The image **wasn't** rebuilt correctly. Here's [an example](https://github.com/paveloom-j/Scats.jl/runs/935437086#step:4:176) of a log.

Example 2:

Workflow file:

```yml
jobs:
  BinderGHP:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push to GitHub Packages
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: "docker.pkg.github.com"
        BINDER_CACHE: true
        IMAGE_NAME: "paveloom-j/scats.jl/binder"
```

The image **was** rebuilt correctly. Here's [an example](https://github.com/paveloom-j/Scats.jl/runs/935473175#step:4:174) of a log.

**Comment by hamelsmu** [comment]
Apologies for my ignorance how do you know the image wasn’t built correctly?  The problem doesn’t jump out at me from the logs that are linked 

Please explain it to me like I am dumb :)

**Comment by Paveloom** [comment]
One of the logs contains 62 steps of a valid image assembly, the other one has just one step of pulling an already built image. By the way, just now noticed that in the one that has a single step, the configuration files are taken from the `binder` folder (that is, the action found `Dockerfile` and uses the already collected image from Docker Hub). When I specify any value for `BINDER_CACHE`, the `binder` directory is ignored and the assembly comes from scratch, relying on configuration files from the root of the repository, which is what I want.

Well, in an earlier part of my [pull request](https://github.com/paveloom-j/Scats.jl/pull/129), I checked manually that the image for GitHub Packages didn't contain TeX packages, even though it was expected. It just took the previous version from Docker Hub (previous commit then), which didn't have them.

> If you switch the order so that DockerHub is second in your build order, is the problem reproducible?

Yes. I'm pretty sure now it happens due to the wrong configuration files being used. This is, by the way, expected in terms of `repo2docker`, but as part of this Action I would like to be able to ignore config files in the `binder` folder, since `Dockerfile` in this folder should only be the result.

**Comment by hamelsmu** [comment]
Is it just the case that you don't want repo2docker to use a cache?  If you want to force repo2docker to not leverage the locally built image, I would recommend separating your two steps into two separate jobs in your workflow file.

Something like this (I didn't check syntax exactly but this should give you a rough idea):

```yaml
jobs:
  Binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push to GitHub Packages
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: "docker.pkg.github.com"
        IMAGE_NAME: "paveloom-j/scats.jl/binder"

  Binder2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Build and push to Docker Hub
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: paveloom
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        COMMIT_MSG: "Binder: update the image tag."
        PUBLIC_REGISTRY_CHECK: true
        IMAGE_NAME: "paveloom/scats.jl-binder"
```
