### ISSUE TITLE
nbgitpuller cannot pull from github to docker hub image

### ISSUE THREAD

**Issue by rdmolony** [jupyterhub/repo2docker-action#81]
**Describe the bug**
I'm currently using an environment repo and a content repo as per [this discussion](https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956) and tried your docker hub action to save the environment repo to docker hub.  

When running https://mybinder.org/v2/gh/codema-dev/projects-sandbox/main?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fcodema-dev%252Fprojects%26urlpath%3Dlab%252Ftree%252Fprojects%252Fbinder.ipynb%26branch%3Dmain pulling the environment image from docker hub mybinder.org build failed with 

![image](https://user-images.githubusercontent.com/50016440/137483593-3095045b-7164-4b84-a137-511427f2bc9d.png)

(see [here](https://github.com/codema-dev/projects-sandbox/pull/1) for more information)

**To Reproduce**
1. Push an environment repo to docker hub by saving this action in `.github/workflows.binder.yaml`

```yaml
name: Binder
on: [push]

jobs:
  binder:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
```

2. Generate a binder link on the environment repo and on the content repo [here](https://jupyterhub.github.io/nbgitpuller/link.html)
3. Click the binder link
 
**Expected behavior**
nbgitpuller pulls from the content repo as expected

---

Thanks a lot for all your work on this action, Binder has been a life saver in opening up our work to the wider public!
